dbtbigquery:
  outputs:
    dev:
      dataset: airbnb_pipeline
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/jpalvim/Desktop/keys/dbtsvcacc.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-wh
      threads: 1
      type: bigquery
  target: dev
dbtlearn:
  outputs:
    dev:
      account: dyjnqdn-ye58241
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
