version: 2

sources:
  - name: airbnb_raw #name
    schema: raw_data #dataset
    database: dbt-wh #project
    tables: 
      - name: raw_hosts
      - name: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
      - name: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}